"""the command line (SPEC.md §12).

the CLI and the web ui are two front doors to one sqlite store (§9a, §14);
neither is authoritative. resolution and tagging are **separate commands**
because the API is slow and rate-limited while tagging is fast and local —
caching resolution means the tag writer can be re-run freely.

nothing here writes to stdout directly: `output.emit` is the single sink, so
the ui can capture exactly what the CLI says.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import shutil
import sys
from dataclasses import fields, replace
from pathlib import Path
from typing import Any

from music_metadata import library_map
from music_metadata.arbitrate import Resolved, arbitrate
from music_metadata.artwork import Artwork, resolve_artwork
from music_metadata.config import DEFAULT_SIDECAR, get, load_env, require
from music_metadata.credit import resolve_credit
from music_metadata.dedup import TrackFile, preference_key
from music_metadata.naming import output_filename, split_title
from music_metadata.output import Level, emit
from music_metadata.probe import ProbedFile, probe_tree
from music_metadata.release import ReleaseCandidate, choose_release, strip_edition
from music_metadata.sources.base import RateLimitedError, SourceError
from music_metadata.sources.beatport import Beatport, Match, classify, tracks_from_raw
from music_metadata.sources.bp_auth import CookieSessionProvider, NullProvider
from music_metadata.sources.discogs import Discogs, release_from_raw
from music_metadata.sources.itunes import Itunes, releases_from_raw
from music_metadata.sources.musicbrainz import (
  MusicBrainz,
  Work,
  recording_from_raw,
  work_from_raw,
)
from music_metadata.sources.spotify import (
  Spotify,
  SpotifyResult,
  candidates_from_raw,
)
from music_metadata.store import Store
from music_metadata.tag import Tags, read_tags, write_tags
from music_metadata.verify import (
  REQUIRED_FIELDS,
  Report,
  duplicate_report,
  gate_g1_identity,
  gate_g2_completeness,
  gate_g4_non_destruction,
  gate_g5_artwork,
  gate_g6_credit,
  gate_g9_no_contamination,
  gate_g11_no_duplicates,
)

# **the operator's tracks arrive from more than one place.** a store download
# and a youtube rip of the same recording sit in different folders, and §11a
# cannot compare what it never saw — the measured cross-format pair was missed
# for exactly this reason. app-managed folders (_Serato_, rekordbox, PioneerDJ)
# are deliberately absent: those are another tool's data (§9).
DEFAULT_LIBRARY = (
  Path.home() / "Music/library",
  Path.home() / "Music/beatport",
  Path.home() / "Music/soundcloud",
)

# a single failure is a track to retry later; this many in a row means the
# service is refusing us and continuing just burns quota against a wall.
_MAX_CONSECUTIVE_ERRORS = 10


def _candidates_for(store: Store, probed: ProbedFile) -> list[ReleaseCandidate]:
  """Re-parse the cached spotify payload for one track. No network.

  Args:
    store: the sidecar.
    probed: the file's local facts.

  Returns:
    The release candidates, empty when nothing is cached.
  """
  if not probed.isrc:
    return []
  raw = store.get_raw(probed.isrc, "spotify")
  return candidates_from_raw(raw) if isinstance(raw, dict) else []


def _overrides_for(map_path: Path) -> dict[str, dict[str, str]]:
  """Load §9b's hand-edited values, keyed by audio md5.

  **This is what makes editing `library.toml` mean anything.** The merge rule
  preserves an edit in the file, but preserving it is not the same as using it:
  until this is read back, a hand-typed ISRC sits in the map and changes no tag.

  Args:
    map_path: the map file. A missing one is normal — it is generated by the
      first run, and an operator who has edited nothing overrides nothing.

  Returns:
    md5 to the fields the operator asserted.
  """
  if not map_path.is_file():
    return {}
  return library_map.read(map_path)


def _effective(probed: ProbedFile, overrides: dict[str, str]) -> ProbedFile:
  """Apply a hand-edited ISRC to a file's local facts.

  The ISRC is not an ordinary override. Every other field is written *after*
  resolution, so overriding it late is enough — but the ISRC is the key the
  lookups are made *with*, so it has to be substituted before any of them run.
  Overriding it at the end would keep the operator's string and none of the
  metadata it was supposed to unlock.

  Args:
    probed: the file's local facts.
    overrides: that file's hand-edited values.

  Returns:
    The facts, with a hand-edited ISRC substituted when one is present.
  """
  isrc = (overrides.get("isrc") or "").strip()
  if not isrc or isrc == probed.isrc:
    return probed
  return replace(probed, isrc=isrc)


def _resolved_for(
  store: Store, probed: ProbedFile, overrides: dict[str, str] | None = None
) -> Resolved:
  """Arbitrate one track from whatever is already cached. No network.

  Args:
    store: the sidecar.
    probed: the file's local facts.
    overrides: hand-edited values from `library.toml` for this file (§9b).

  Returns:
    The resolved tags.
  """
  overrides = overrides or {}
  probed = _effective(probed, overrides)
  credit = None
  work: Work | None = None
  itunes_release = None
  discogs_release = None
  artwork: Artwork | None = None
  # bound before the branch: the 55 files with no ISRC (§2) take none of it,
  # and an unbound name here crashes `apply` on exactly those tracks.
  beatport_match: Match | None = None
  if probed.isrc:
    recording = recording_from_raw(store.get_raw(probed.isrc, "musicbrainz"))
    if recording is not None:
      credit = recording.credit
    raw_work = store.get_raw(probed.isrc, "work")
    if raw_work is not None:
      work = work_from_raw(raw_work)
    itunes_raw = store.get_raw(probed.isrc, "itunes")
    if itunes_raw is not None:
      releases = releases_from_raw(itunes_raw)
      itunes_release = releases[0] if releases else None
    discogs_release = release_from_raw(store.get_raw(probed.isrc, "discogs"))
    artwork = _artwork_from_store(store, probed.isrc)
    beatport_match = _beatport_from_store(store, probed)

  return arbitrate(
    probed,
    _candidates_for(store, probed),
    searched=store.get_raw(probed.isrc, "spotify") is not None
    if probed.isrc
    else False,
    musicbrainz=credit,
    work=work,
    itunes=itunes_release,
    discogs=discogs_release,
    artwork=artwork,
    beatport=beatport_match,
    overrides=overrides,
  )


def _beatport_from_store(store: Store, probed: ProbedFile) -> Match | None:
  """Re-derive a beatport match from the cached payload. No network.

  The G3 class is recomputed rather than stored, so a change to the tolerance
  replays against what was already fetched (§9a).

  Args:
    store: the sidecar.
    probed: the file's local facts, for the duration comparison.

  Returns:
    The match, or None when beatport had nothing.
  """
  if not probed.isrc:
    return None
  tracks = tracks_from_raw(store.get_raw(probed.isrc, "beatport"))
  if not tracks:
    return None
  field_class, delta = classify(probed.duration_s, tracks[0])
  return Match(tracks[0], "cached", field_class, delta)


def _artwork_from_store(store: Store, isrc: str) -> Artwork | None:
  """Load the artwork bytes already fetched for a recording.

  §9a: 3-4 GB of covers are fetched once. re-reading them from disk is what
  makes `apply` re-runnable without re-downloading the library's artwork.

  Args:
    store: the sidecar.
    isrc: the recording's ISRC.

  Returns:
    The artwork, or None when none was cached.
  """
  rows = store.query("SELECT * FROM artwork WHERE isrc = ?", (isrc,))
  if not rows or not rows[0]["local_path"]:
    return None
  path = Path(rows[0]["local_path"])
  if not path.is_file():
    return None
  return Artwork(
    data=path.read_bytes(),
    mime="image/jpeg",
    width=int(rows[0]["width"] or 0),
    candidate=rows[0]["candidate"] or "cached",
    source_release=rows[0]["source_release"] or "",
    url=rows[0]["url_template"] or "",
  )


def render_credit_from_tags(resolved: Resolved) -> str:
  """Render the credit the resolver chose, as the review queue shows it.

  Args:
    resolved: the arbitrated result.

  Returns:
    The artist plus any featured artists carried in the title.
  """
  title = resolved.tags.title or ""
  _, _, tail = title.partition("(ft. ")
  featured = tail.partition(")")[0] if tail else ""
  artist = resolved.tags.artist or ""
  return f"{artist} (ft. {featured})" if featured else artist


def _map_row(
  probed: ProbedFile,
  resolved: Resolved,
  chosen: ReleaseCandidate | None,
) -> dict[str, str]:
  """Build one `library.toml` row.

  Args:
    probed: the file's local facts.
    resolved: the arbitrated tags.
    chosen: the release §7b picked, whose track id gives the spotify link.

  Returns:
    The field values for the map. An empty service field is the worklist
    entry §9b describes, not a gap to hide.
  """
  spotify_url = ""
  if chosen is not None and chosen.track_id:
    spotify_url = f"https://open.spotify.com/track/{chosen.track_id}"
  return {
    "file": probed.path.name,
    "title": resolved.tags.title or "",
    "artist": resolved.tags.artist or "",
    "album": resolved.tags.album or "",
    "isrc": probed.isrc or "",
    "spotify": spotify_url,
    "itunes": "",
    "beatport": "",
  }


def write_map(store: Store, map_path: Path) -> int:
  """Build `library.toml` from the sidecar alone. No probing, no network.

  §9b: **every run produces one file**, and it is "the map, the override file
  and the worklist at once". binding it to `apply` would mean writing 1,494
  tagged copies just to see which tracks still need a beatport URL — the exact
  loop §9b describes is resolve, read the map, paste a URL, re-run.

  Building it from the `files` table rather than re-probing also makes it cheap
  enough to call mid-run.

  Args:
    store: the sidecar.
    map_path: where to write the map.

  Returns:
    How many entries were written.
  """
  entries = []
  on_disk = library_map.read(map_path)
  for row in store.query("SELECT * FROM files ORDER BY path"):
    probed = ProbedFile(
      path=Path(row["path"]),
      audio_md5=row["audio_md5"],
      duration_s=float(row["duration_s"]),
      isrc=row["isrc_from_tag"],
      tags={},
    )
    resolved = _resolved_for(store, probed)
    chosen = choose_release(_candidates_for(store, probed))
    entries.append(
      library_map.merge(
        probed.audio_md5,
        _map_row(probed, resolved, chosen),
        on_disk.get(probed.audio_md5, {}),
        store.get_generated(probed.audio_md5),
      )
    )
  library_map.write(map_path, entries, store)
  return len(entries)


def cmd_probe(args: argparse.Namespace) -> int:
  """Survey the library's local tag facts. No network.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  with Store.open(args.sidecar) as store:
    total = with_isrc = 0
    for probed in probe_tree(*args.library):
      store.put_file(
        path=str(probed.path),
        audio_md5=probed.audio_md5,
        duration_s=probed.duration_s,
        isrc=probed.isrc,
        mtime=probed.path.stat().st_mtime,
      )
      total += 1
      with_isrc += bool(probed.isrc)
      if total % 100 == 0:
        emit(f"probed {total}")

    emit(f"probed {total} files")
    emit(
      f"with ISRC {with_isrc} ({with_isrc / total * 100:.1f}%)" if total else "empty"
    )
    emit(f"without ISRC {total - with_isrc}")
  return 0


def cmd_resolve(args: argparse.Namespace) -> int:
  """Resolve identities through the source tiers into the sidecar.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  load_env()
  with Store.open(args.sidecar) as store:
    # **a hand-typed ISRC has to be resolved *with*, not merely written.** the
    # 55 files with no ISRC tag (§2) are invisible to this query, so an operator
    # who fills one into `library.toml` would otherwise see their edit preserved
    # in the file and nothing fetched against it.
    overrides = _overrides_for(args.map)
    rows: list[dict[str, Any]] = []
    adopted = 0
    for source in store.query("SELECT * FROM files ORDER BY path"):
      row = dict(source)
      hand = (overrides.get(row["audio_md5"], {}).get("isrc") or "").strip()
      if not row["isrc_from_tag"] and hand:
        row["isrc_from_tag"] = hand
        adopted += 1
      if row["isrc_from_tag"]:
        rows.append(row)
    if adopted:
      emit(f"{adopted} ISRC(s) taken from hand-edits in {args.map} (§9b)")
    if args.limit:
      rows = rows[: args.limit]
    if not rows:
      emit("nothing to resolve — run `probe` first", level=Level.WARN)
      return 1

    spotify = Spotify(require("SPOTIFY_CLIENT_ID"), require("SPOTIFY_CLIENT_SECRET"))
    musicbrainz = MusicBrainz()
    itunes = Itunes()
    discogs_token = get("DISCOGS_TOKEN")
    discogs = Discogs(discogs_token) if discogs_token else None
    # §5: tier 3 is optional by construction. with no cookie there is no
    # provider, beatport contributes nothing, and the run completes.
    provider = NullProvider() if args.no_beatport else CookieSessionProvider()
    beatport = Beatport(tokens=provider) if provider.available else None
    if beatport is None and not args.no_beatport:
      emit(
        "beatport: no session cookie, genre falls back to discogs/itunes",
        level=Level.WARN,
      )
    art_dir = args.sidecar.parent / "artwork"
    art_dir.mkdir(parents=True, exist_ok=True)
    fetched = cached = mb_hits = mb_misses = mb_errors = 0
    spotify_errors = 0
    art_hits = art_misses = bp_hits = bp_misses = 0
    try:
      for index, row in enumerate(rows, start=1):
        isrc = row["isrc_from_tag"]

        # **each source is cached independently.** §9a: only rows with no raw
        # payload are re-fetched. checking one source and skipping the whole
        # track would mean a source added later — beatport, once a cookie
        # exists — could never backfill without discarding everything else.
        def missing(service: str, isrc: str = isrc) -> bool:
          return args.refetch or store.get_raw(isrc, service) is None

        if not any(
          missing(service)
          for service in ("spotify", "musicbrainz", "itunes", "discogs", "beatport")
        ):
          cached += 1
          continue

        if missing("spotify"):
          try:
            result = spotify.search_isrc(isrc)
            store.put_raw(isrc, "spotify", result.raw)
          except RateLimitedError as exc:
            # **a quota window ends the pass, it does not skip a track.** the
            # per-track `continue` below skips musicbrainz, itunes and discogs
            # too, so carrying on after a ban banks nothing at all — it just
            # walks the remaining tracks re-asking a service that has already
            # said no for the next twelve hours.
            resume = datetime.datetime.now() + datetime.timedelta(
              seconds=exc.retry_after
            )
            emit(
              f"{exc} after {spotify.requests} requests this run — "
              f"stopping at track {index} of {len(rows)}. "
              f"everything fetched so far is cached; "
              f"re-run after {resume:%a %H:%M} to resume.",
              level=Level.ERROR,
            )
            break
          except SourceError as exc:
            # **one track must never abort the run.** spotify rate-limits at
            # scale, and an uncaught 429 here killed a 1,439-track pass at
            # track 61 — losing nothing cached, but stopping everything. the
            # track is left unresolved and picked up on the next pass.
            spotify_errors += 1
            emit(f"[{index}/{len(rows)}] {isrc} — spotify: {exc}", level=Level.WARN)
            if spotify_errors >= _MAX_CONSECUTIVE_ERRORS:
              emit(
                f"spotify failed {spotify_errors} times in a row — stopping. "
                f"everything fetched so far is cached; re-run to resume.",
                level=Level.ERROR,
              )
              break
            continue
          spotify_errors = 0
        else:
          result = SpotifyResult(
            candidates=candidates_from_raw(store.get_raw(isrc, "spotify")), raw=None
          )

        # tier 2. a miss here is normal (F31), and so is the service being
        # briefly unavailable — musicbrainz 503s routinely (F30/F52). neither
        # may abort the run: §5's rule that a flaky tier cannot stop the
        # pipeline is not specific to beatport, and losing an hour of resolved
        # identities to one bad minute would be the expensive failure.
        recording = None
        if missing("musicbrainz"):
          try:
            recording, raw_mb = musicbrainz.recording_for_isrc(isrc)
            store.put_raw(isrc, "musicbrainz", raw_mb)
          except SourceError as exc:
            mb_errors += 1
            emit(f"  musicbrainz unavailable for {isrc}: {exc}", level=Level.WARN)
        else:
          recording = recording_from_raw(store.get_raw(isrc, "musicbrainz"))

        if recording is None:
          mb_misses += 1
        else:
          mb_hits += 1
          if recording.work_id and missing("work"):
            try:
              _, raw_work = musicbrainz.work(recording.work_id)
              store.put_raw(isrc, "work", raw_work)
            except SourceError as exc:
              mb_errors += 1
              emit(f"  musicbrainz work failed for {isrc}: {exc}", level=Level.WARN)

        # tiers 2 and 3: itunes for the artwork chain and a genre fallback,
        # discogs for label. both are optional — a failure flags the track
        # rather than stopping the run (§5's rule applied beyond beatport).
        chosen = choose_release(result.candidates)
        if chosen is not None:
          album_artist = ", ".join(chosen.album_artists)
          art = None
          attempted_artwork = missing("itunes")
          if attempted_artwork:
            try:
              # the album search doubles as the genre fallback source (§7), so
              # its payload is cached rather than thrown away after the chain.
              # stripped for the same reason `resolve_artwork` strips it:
              # itunes returns nothing for a name carrying `(Deluxe)`.
              album_hits = itunes.search_albums(
                f"{album_artist} {strip_edition(chosen.album_name)}".strip()
              )
              store.put_raw(isrc, "itunes", album_hits.raw)
              # **candidate C needs the image spotify already gave us** (§7c).
              # it was implemented and never supplied, so a track itunes could
              # not find was flagged `no-artwork` while a verified 640px cover
              # sat unused in the cached payload.
              art = resolve_artwork(
                itunes,
                chosen.album_name,
                album_artist,
                chosen.track_name,
                spotify_image_url=chosen.image_url,
              )
            except SourceError as exc:
              emit(f"  itunes unavailable for {isrc}: {exc}", level=Level.WARN)

          if art is None:
            # a track whose artwork was already fetched is not a miss; only
            # count an attempt that found nothing (G5).
            art_misses += attempted_artwork
          else:
            art_hits += 1
            destination = art_dir / f"{isrc}.jpg"
            destination.write_bytes(art.data)
            store.put_artwork(
              isrc=isrc,
              source_release=art.source_release,
              candidate=art.candidate,
              url_template=art.url,
              width=art.width,
              sha256=art.sha256,
              local_path=str(destination),
            )

          if discogs is not None and missing("discogs"):
            try:
              release_id, raw_search = discogs.search_release_id(
                album_artist, chosen.album_name
              )
              if release_id is not None:
                _, raw_release = discogs.release(release_id)
                store.put_raw(isrc, "discogs", raw_release)
            except SourceError as exc:
              emit(f"  discogs unavailable for {isrc}: {exc}", level=Level.WARN)

        # tier 3. never raises; a miss and an outage look the same from here,
        # which is what makes the tier droppable (§5).
        if beatport is not None and missing("beatport"):
          parsed_title = split_title(chosen.track_name) if chosen else None
          artist = chosen.track_artists[0] if chosen and chosen.track_artists else ""
          if parsed_title is not None:
            match, raw_bp = beatport.find(
              isrc=isrc,
              artist=artist,
              name=parsed_title.name,
              mix_name=parsed_title.mix,
              local_duration_s=float(row["duration_s"]),
            )
            store.put_raw(isrc, "beatport", raw_bp)
            if match is not None:
              bp_hits += 1
            else:
              bp_misses += 1

        fetched += 1
        # §9b: the map is the worklist. flushing it periodically means a long
        # run is inspectable while it is still going, not only afterwards.
        if fetched % 100 == 0:
          write_map(store, args.map)
        credited = "credit" if recording else "no-credit"
        emit(
          f"[{index}/{len(rows)}] {isrc} — "
          f"{len(result.candidates)} releases, {credited}"
        )
    finally:
      spotify.close()
      musicbrainz.close()
      itunes.close()
      if discogs is not None:
        discogs.close()
      if beatport is not None:
        beatport.close()

    written = write_map(store, args.map)
    emit(f"wrote {args.map} ({written} entries)")
    emit(f"resolved {fetched} fetched, {cached} already cached")
    if spotify_errors:
      emit(f"spotify failed on {spotify_errors} track(s)", level=Level.WARN)
    emit(f"musicbrainz {mb_hits} found, {mb_misses} missing, {mb_errors} unavailable")
    emit(f"artwork {art_hits} verified, {art_misses} unverified (G5)")
    if beatport is not None:
      emit(f"beatport {bp_hits} matched, {bp_misses} not listed")
    else:
      emit("beatport skipped — genre from discogs/itunes")
  return 0


def _changes(current: Tags, proposed: Tags) -> list[tuple[str, str, str]]:
  """List the fields that would change.

  Args:
    current: what the file carries now.
    proposed: what the resolver would write.

  Returns:
    Field, old value, new value — for fields that actually differ.
  """
  out = []
  for spec in fields(Tags):
    if spec.name in {"artwork", "artwork_mime"}:
      continue
    old = getattr(current, spec.name)
    new = getattr(proposed, spec.name)
    if new is not None and old != new:
      out.append((spec.name, str(old or ""), str(new)))
  return out


def cmd_diff(args: argparse.Namespace) -> int:
  """Show the proposed change set, old to new. Writes nothing.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  with Store.open(args.sidecar) as store:
    # the ui reads this table rather than re-probing the library (§14).
    store.clear_proposed()
    overrides = _overrides_for(args.map)
    shown = 0
    for probed in probe_tree(*args.library):
      if args.limit and shown >= args.limit:
        break
      resolved = _resolved_for(store, probed, overrides.get(probed.audio_md5))
      changes = _changes(read_tags(probed.path), resolved.tags)
      if not changes:
        continue
      shown += 1
      emit(probed.path.name)
      for field_name, old, new in changes:
        source = resolved.provenance.get(field_name, "?")
        emit(f"  {field_name:<16} {old!r} -> {new!r}  [{source}]")
        store.put_proposed(
          audio_md5=probed.audio_md5,
          file=probed.path.name,
          field=field_name,
          old_value=old,
          new_value=new,
          source=source,
        )
      if resolved.flags:
        emit(f"  flags: {', '.join(resolved.flags)}", level=Level.WARN)
    emit(f"{shown} tracks would change")
  return 0


def _unique_name(name: str, taken: set[str]) -> str:
  """Disambiguate an output name that is already in use.

  Two different recordings can legitimately render to one name — a track and
  its own radio edit, say. Overwriting would silently lose one, so the second
  gets a numbered suffix.

  Args:
    name: the preferred filename.
    taken: names already written this run.

  Returns:
    `name`, or `name` with the lowest free ` (n)` suffix before the extension.
  """
  if name not in taken:
    return name
  stem, _, suffix = name.rpartition(".")
  counter = 2
  while f"{stem} ({counter}).{suffix}" in taken:
    counter += 1
  return f"{stem} ({counter}).{suffix}"


def cmd_apply(args: argparse.Namespace) -> int:
  """Write tagged copies to the output tree. The source is never touched.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  args.out.mkdir(parents=True, exist_ok=True)
  with Store.open(args.sidecar) as store:
    written = 0
    # **G11 asserts no two output files share an audio md5.** the source tree
    # holds three byte-identical pairs (§11a class A), and copying both sides
    # of each would fail the gate the run is trying to pass. the source is
    # never touched (§9) — the duplicate is simply not emitted, and is reported.
    emitted_audio: dict[str, str] = {}
    # two different recordings can still resolve to one name, so names are
    # tracked separately from audio and disambiguated rather than overwritten.
    used_names: set[str] = set()
    skipped_duplicates = 0
    overrides = _overrides_for(args.map)
    # **emission order decides which copy of a duplicate survives**, so it is
    # ranked rather than left to the filesystem: `CHICA 305 (2).aiff` sorts
    # ahead of `CHICA 305.aiff`, and taking files as they came would keep every
    # re-download and drop every original.
    for probed in sorted(
      probe_tree(*args.library), key=lambda f: preference_key(str(f.path))
    ):
      if args.limit and written >= args.limit:
        break
      resolved = _resolved_for(store, probed, overrides.get(probed.audio_md5))

      # §8's gates refuse to guess; each refusal becomes a queue entry rather
      # than a line in a log nobody reads (§14).
      store.resolve_review(probed.audio_md5)
      if resolved.flags:
        existing = read_tags(probed.path)
        for flag in resolved.flags:
          # show what the decision is actually between. for a credit
          # disagreement the two sides often share a TPE1 and differ only in
          # who is featured, so a bare artist field shows nothing to decide.
          alternative = resolved.alternatives.get(flag)
          if alternative is not None:
            proposed = render_credit_from_tags(resolved)
            current = alternative
          else:
            proposed = resolved.tags.artist or ""
            current = existing.artist or ""
          store.put_review(
            audio_md5=probed.audio_md5,
            flag=flag,
            file=probed.path.name,
            proposed=proposed,
            current=current,
            source=resolved.provenance.get("artist", ""),
          )

      if probed.audio_md5 in emitted_audio:
        skipped_duplicates += 1
        emit(
          f"skipped {probed.path.name} — same audio as "
          f"{emitted_audio[probed.audio_md5]} (§11a class A)",
          level=Level.WARN,
        )
        continue

      # §9: emit a fully tagged copy, leave the source untouched. the name is
      # rebuilt from the resolved tags rather than carried over, so the file on
      # disk agrees with what is written inside it.
      name = output_filename(
        resolved.tags.title or "",
        resolved.tags.artist or "",
        probed.path.suffix,
      )
      name = _unique_name(name, used_names)
      used_names.add(name)
      destination = args.out / name
      shutil.copy2(probed.path, destination)
      write_tags(destination, resolved.tags)
      emitted_audio[probed.audio_md5] = name
      written += 1

      emit(f"wrote {destination.name}")

    emit(f"wrote {written} tagged copies to {args.out}")
    if skipped_duplicates:
      emit(
        f"skipped {skipped_duplicates} byte-identical duplicate(s) — "
        f"the source tree still holds them (§9)",
        level=Level.WARN,
      )
    emit(f"wrote {args.map} ({write_map(store, args.map)} entries)")
    for flag, count in store.review_counts().items():
      emit(f"flagged {count} × {flag}")
  return 0


def tree_checksum(*roots: Path) -> str:
  """One hash over every audio file in the source trees, for G4.

  §8: the source tree's bytes are unchanged **asserted by checksum, not by
  inspection**. hashing the container rather than the decoded audio is right
  here — a tag write changes the container, which is exactly what must not
  happen to the source.

  Every scanned root is covered, since every one of them is a source tree the
  run promises not to touch.

  Args:
    *roots: the directories to hash. A missing root contributes nothing.

  Returns:
    A hex digest over every audio file, in sorted path order. The full path is
    hashed rather than the bare name, so two roots holding same-named files
    stay distinguishable.
  """
  digest = hashlib.sha256()
  for root in roots:
    if not root.is_dir():
      continue
    for path in sorted(root.rglob("*")):
      if path.is_file() and path.suffix.lower() in {".aiff", ".aif", ".wav"}:
        digest.update(str(path).encode())
        digest.update(hashlib.sha256(path.read_bytes()).digest())
  return digest.hexdigest()


def cmd_verify(args: argparse.Namespace) -> int:
  """Assert the gates over an output tree (§8).

  Args:
    args: parsed arguments.

  Returns:
    0 when every gate met its target, 1 otherwise.
  """
  with Store.open(args.sidecar) as store:
    rows = store.query("SELECT * FROM files ORDER BY path")
    if not rows:
      emit("nothing to verify — run `probe` first", level=Level.WARN)
      return 1

    with_isrc = [r for r in rows if r["isrc_from_tag"]]
    resolved = sum(
      1 for r in with_isrc if store.get_raw(r["isrc_from_tag"], "spotify") is not None
    )

    source_files = [
      TrackFile(
        path=r["path"],
        audio_md5=r["audio_md5"],
        duration_s=float(r["duration_s"]),
        isrc=r["isrc_from_tag"],
      )
      for r in rows
    ]

    output = list(probe_tree(args.out)) if args.out.is_dir() else []
    out_files = [
      TrackFile(
        path=str(p.path), audio_md5=p.audio_md5, duration_s=p.duration_s, isrc=p.isrc
      )
      for p in output
    ]

    complete = 0
    contamination = 0
    artwork_present = 0
    by_md5 = {r["audio_md5"]: r for r in rows}
    for probed in output:
      tags = read_tags(probed.path)
      if all(getattr(tags, name) is not None for name in REQUIRED_FIELDS):
        complete += 1
      if tags.artwork:
        artwork_present += 1
      origin = by_md5.get(probed.audio_md5)
      # G9: the written ISRC must be the file's own, never a source's.
      if origin and origin["isrc_from_tag"] and tags.isrc != origin["isrc_from_tag"]:
        contamination += 1

    counts = store.review_counts()

    # G6's population is **tracks where a cross-check actually happened** —
    # musicbrainz had the recording and the filename carried a credit. counting
    # every track would dilute the rate with tracks that were never compared.
    agree = disagree = 0
    for row in with_isrc:
      recording = recording_from_raw(store.get_raw(row["isrc_from_tag"], "musicbrainz"))
      if recording is None:
        continue
      result = resolve_credit(Path(row["path"]).stem, musicbrainz=recording.credit)
      if result.agrees is True:
        agree += 1
      elif result.agrees is False:
        disagree += 1

    duplicates, dup_gate = duplicate_report(source_files)

    report = Report(duplicates=duplicates)
    report.gates.append(gate_g1_identity(len(with_isrc), resolved))
    report.gates.append(gate_g2_completeness(complete, len(output)))
    if args.checksum_before:
      report.gates.append(
        gate_g4_non_destruction(args.checksum_before, tree_checksum(*args.library))
      )
    report.gates.append(gate_g5_artwork(artwork_present, counts.get("no-artwork", 0)))
    report.gates.append(gate_g6_credit(agree=agree, disagree=disagree))
    report.gates.append(gate_g9_no_contamination(contamination))
    report.gates.append(gate_g11_no_duplicates(out_files))
    report.gates.append(dup_gate)

    for gate in report.gates:
      emit(str(gate))
      if gate.detail:
        emit(f"      {gate.detail}")

    if duplicates:
      emit("")
      emit("§11a duplicates — class A is auto-resolvable, class B is not:")
      for entry in duplicates:
        emit(f"  [{entry.kind.value}] {entry.reason}")
        for member in entry.files:
          emit(f"      {member.path}")

    emit("")
    if report.passed:
      emit(f"all {len(report.gates)} gates met their target")
      return 0
    emit(f"{len(report.failures)} gate(s) did not meet target", level=Level.ERROR)
    return 1


def cmd_map(args: argparse.Namespace) -> int:
  """Render the map for scanning (§9c). Read-only.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  # §9b: the map is derived from the sidecar, so a run that was interrupted
  # before its final flush has lost nothing — regenerate rather than telling
  # the operator to re-fetch 1,439 tracks they have already paid for.
  if args.regenerate or not args.map.is_file():
    with Store.open(args.sidecar) as store:
      count = write_map(store, args.map)
    emit(f"regenerated {args.map} from the sidecar ({count} entries)")

  rows = library_map.read(args.map)
  if not rows:
    emit(f"no map at {args.map} — run `resolve` first", level=Level.WARN)
    return 1

  shown = 0
  for md5, values in rows.items():
    if args.missing and values.get(args.missing):
      continue
    if args.no_isrc and values.get("isrc"):
      continue
    shown += 1
    emit(
      "\t".join(
        [
          md5,
          values.get("file", ""),
          values.get("isrc", ""),
          values.get("spotify", ""),
          values.get("itunes", ""),
          values.get("beatport", ""),
        ]
      )
    )
  emit(f"{shown} of {len(rows)} rows")
  return 0


def cmd_checksum(args: argparse.Namespace) -> int:
  """Print a tree's checksum, so G4 can be asserted across a run.

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  emit(tree_checksum(*args.library))
  return 0


def cmd_serve(args: argparse.Namespace) -> int:
  """Run the web ui (§14).

  Args:
    args: parsed arguments.

  Returns:
    Process exit code.
  """
  from music_metadata.web.app import serve

  emit(f"serving on http://{args.host}:{args.port}")
  serve(args.sidecar, host=args.host, port=args.port)
  return 0


def build_parser() -> argparse.ArgumentParser:
  """Build the argument parser.

  Returns:
    The configured parser.
  """
  parser = argparse.ArgumentParser(prog="music-metadata", description=__doc__)
  parser.add_argument("--sidecar", type=Path, default=DEFAULT_SIDECAR)
  sub = parser.add_subparsers(dest="command", required=True)

  probe = sub.add_parser("probe", help="local tag survey, no network")
  probe.add_argument(
    "--library",
    type=Path,
    nargs="+",
    default=list(DEFAULT_LIBRARY),
    help="folders to scan; repeatable",
  )
  probe.set_defaults(func=cmd_probe)

  resolve = sub.add_parser("resolve", help="resolve identities into the sidecar")
  resolve.add_argument("--limit", type=int, default=0)
  resolve.add_argument("--refetch", action="store_true", help="ignore the cache")
  resolve.add_argument(
    "--no-beatport", action="store_true", help="skip tier 3 entirely (SPEC.md §5)"
  )
  resolve.add_argument("--map", type=Path, default=Path("library.toml"))
  resolve.set_defaults(func=cmd_resolve)

  diff = sub.add_parser("diff", help="proposed changes, old to new")
  diff.add_argument("--map", type=Path, default=Path("library.toml"))
  diff.add_argument(
    "--library",
    type=Path,
    nargs="+",
    default=list(DEFAULT_LIBRARY),
    help="folders to scan; repeatable",
  )
  diff.add_argument("--limit", type=int, default=0)
  diff.set_defaults(func=cmd_diff)

  apply_ = sub.add_parser("apply", help="write tagged copies")
  apply_.add_argument(
    "--library",
    type=Path,
    nargs="+",
    default=list(DEFAULT_LIBRARY),
    help="folders to scan; repeatable",
  )
  apply_.add_argument("--out", type=Path, required=True)
  apply_.add_argument("--map", type=Path, default=Path("library.toml"))
  apply_.add_argument("--limit", type=int, default=0)
  apply_.set_defaults(func=cmd_apply)

  verify = sub.add_parser("verify", help="assert the gates over an output tree")
  verify.add_argument(
    "--library",
    type=Path,
    nargs="+",
    default=list(DEFAULT_LIBRARY),
    help="folders to scan; repeatable",
  )
  verify.add_argument("--out", type=Path, required=True)
  verify.add_argument(
    "--checksum-before",
    help="the source tree's checksum before the run, to assert G4",
  )
  verify.set_defaults(func=cmd_verify)

  checksum = sub.add_parser("checksum", help="hash a tree, for G4")
  checksum.add_argument(
    "--library",
    type=Path,
    nargs="+",
    default=list(DEFAULT_LIBRARY),
    help="folders to scan; repeatable",
  )
  checksum.set_defaults(func=cmd_checksum)

  map_ = sub.add_parser("map", help="render the map for scanning")
  map_.add_argument("--map", type=Path, default=Path("library.toml"))
  map_.add_argument("--missing", help="only rows where this field is empty")
  map_.add_argument("--no-isrc", action="store_true", help="only rows with no ISRC")
  map_.add_argument(
    "--regenerate",
    action="store_true",
    help="rebuild the map from the sidecar before rendering",
  )
  map_.set_defaults(func=cmd_map)

  serve_ = sub.add_parser("serve", help="run the web ui")
  serve_.add_argument("--host", default="127.0.0.1")
  serve_.add_argument("--port", type=int, default=8765)
  serve_.set_defaults(func=cmd_serve)

  return parser


def main(argv: list[str] | None = None) -> int:
  """Entry point.

  Args:
    argv: arguments, defaulting to `sys.argv[1:]`.

  Returns:
    Process exit code.
  """
  args = build_parser().parse_args(argv)
  result: int = args.func(args)
  return result


if __name__ == "__main__":
  sys.exit(main())
